services:
    cosmos-app.sbif-api:
        class: CosmosApp\SbifApiBundle\Services\SbifApi
        arguments:
            -

    cosmos-app.sbif-api.dolar:
        class: CosmosApp\SbifApiBundle\Services\Dolar
        arguments: ["@cosmos-app.sbif-api"]
