services:
    cosmos_app.sbif_api:
        class: CosmosApp\SbifApiBundle\Services\SbifApi
        arguments:
            -

    cosmos_app.sbif_api.dolar:
        class: CosmosApp\SbifApiBundle\Services\Dolar
        arguments: ["@cosmos-app.sbif-api"]
