dist: trusty
sudo: false
language: php

php:
    - 5.5.9

git:
    depth: 1

env:
    - SYMFONY_VERSION=2.7.*

before_install:
    - cp phpunit.xml.dist phpunit.xml
    - travis_retry composer self-update

install:
    - travis_retry composer update --prefer-dist --optimize-autoloader -vvv

script:
    - ./bin/phpunit --configuration phpunit.xml
